### PR TITLE
Style to PEP8

### PR DESCRIPTION
**Pull request by Daniel-Fernandez-951**
Working, no breaking changes after PEP8 style tweaks.

### CODE REVIEW

**Review by KWeatherwalks — APPROVED** [review]
Excellent. I like how you broke down the request into multiple commits, each with a clear message.

**Review by brett-doffing — APPROVED** [review]
A much needed cleanup, and well implemented.

**Review by francislabountyjr — APPROVED** [review]
Makes code cleaner and easier to understand. Much needed addition.

**Review by JenFaith — APPROVED** [review]
These changes make the file much more readable

**Pull request merged**
