### PR TITLE
Replace old README with new README

### PR DESCRIPTION
**Pull request by KWeatherwalks**
The old documentation was good, but we wanted to create a consistent style across codebases for the main README.md files located at the root of each repository (FE, BE, DS)
This request
- renames README.md to Labs32README.md so it may be referenced while we craft the new document
- replaces README.md with the start of a new document

Future work on this file will need to improve and add to:
- Our Role section, to describe what this team (and past teams) has done and what the next team can improve on.
- Files section, to give a brief summary of how each piece of this repository (files, folders, etc.) has been used and why it's there.
- any additional installation steps that are currently missing from the process

This is the first step in improving the new documentation.  The next step will be improving this document. Then, we can create READMEs for each folder that explain what each file in that folder does, who created it, and for what purpose.
Please help us make it better by adding anything that may be helpful to future teams.

### CODE REVIEW

**Review by Daniel-Fernandez-951 — APPROVED** [review]
Much needed! Thank you for taking the lead on this project.

**Review by JenFaith — APPROVED** [review]
I like the added detail here. Looks great to me!

**Review by ren-curry — APPROVED** [review]
The rewrite of the document and new formatting is great, especially to provide consistency across product.

**Review by francislabountyjr — APPROVED** [review]
Very useful addition. Really like the roadmap for future work as well.

**Review by brett-doffing — APPROVED** [review]
Nice clarifying documentation update.

**Pull request merged**
