### PR TITLE
Update ocr.py GetJudge Class to include more judges

### PR DESCRIPTION
**Pull request by francislabountyjr**
Judge webscraping code updated to use justice.gov sites rather than wikipedia for a more inclusive list of immigration judges.

### CODE REVIEW

**Review by brett-doffing — APPROVED** [review]
I have verified that these links pull the same judges, and more.

**Review by ren-curry — APPROVED** [review]
I agree with this code change as it brings in the official government source for Judge information rather than the community edited source of Wikipedia

**Review by Daniel-Fernandez-951 — APPROVED** [review]
Looks great, gets every judge from Immigration Court and Board of Immigration Appeals.

**Comment by JenFaith** [comment]
This is a great addition because now we'll be capturing more of the judges!

**Review by JenFaith — APPROVED** [review]
This is a great addition because now we'll be capturing more of the judges!

**Comment by FrankBellamy** [comment]
Pulling judges from the official source is good.

**Comment by brett-doffing** [comment]
While I suggested this PR be made, upon closer inspection of what we need, these two links are pulling two distinct lists of judges, namely Appellate judges and Immigration Judges, and the `GetJudge` class is currently only being used for Appellate Judges, whereby the Immigration Judges aren't being utilized at all, so I might question whether this should be merged, or perhaps maybe even suggest it be closed since such changes may not be necessary here? Perhaps keeping the appellate link may be worthwhile instead of the wikipedia link?

**Comment by brett-doffing** [comment]
Never mind lol, got merged, which is fine and good, probably better because I can clean it up.

**Pull request merged**
