### PR TITLE
commented out code in ocr.py that was commented out in BIA_Scraper.py

### PR DESCRIPTION
**Pull request by boscolio**

### CODE REVIEW

**Review by rassamyjs — COMMENTED** [review]
Code shows what you commented out. It is trouble shooting some issues we had when the code was inherited. We are hoping this change will help with deployment.

**Review by rassamyjs — APPROVED** [review]
see prev comment

**Review by Jace-Hambrick — COMMENTED** [review]
This code was giving trouble. We're hoping that this will help us troubleshoot why the scrapper wasn't working properly when we inherited it from labs 31.

**Review by Jace-Hambrick — APPROVED** [review]
See previous comment

**Pull request merged**
