### PR TITLE
Update SCRAPER_INFO.md

### PR DESCRIPTION
**Pull request by brett-doffing**
Added some updates for things I worked on.

### CODE REVIEW

**Review by KWeatherwalks — CHANGES_REQUESTED** [review]
I like the detail provided. Thank you for including links to the notebook.
We should get PR #111 approved ASAP and then update this link to reflect the file's location in the repo.

**Review by JenFaith — APPROVED** [review]
These are great updates to the documentation and will help the next team know where to start.

**Comment by Daniel-Fernandez-951** [comment]
> I like the detail provided. Thank you for including links to the notebook.
> We should get PR #111 approved ASAP and then update this link to reflect the file's location in the repo.

I agree, I will approve once #111 is merged.

**Review by Daniel-Fernandez-951 — APPROVED** [review]
Great detailed information included here.

**Review by joeyMckinney — APPROVED** [review]
love the additional information.

**Review by KWeatherwalks — APPROVED** [review]
Thanks for implementing the changes. This is good to go!

**Pull request merged**
