### PR TITLE
added dummy data to fields in ocr.py and BIA_Scraper.py

### PR DESCRIPTION
**Pull request by boscolio**

### CODE REVIEW

**Review by rassamyjs — COMMENTED** [review]
This change creates dummy data to fields ocr.py and the scraper.py. Added so we can connect to BE

**Review by rassamyjs — APPROVED** [review]

**Review by rassamyjs — APPROVED** [review]

**Review by rassamyjs — COMMENTED** [review]
This commit adds dummy data so the BE has fields they can connect to.

**Review by rassamyjs — APPROVED** [review]
See prev comment

**Review by Jace-Hambrick — COMMENTED** [review]
Adding dummy data so we can connect with BE.
Changed the Fields in OCR.py to reflect BE

**Review by Jace-Hambrick — APPROVED** [review]
See comments

**Review by rassamyjs — APPROVED** [review]
see prev comment

**Review by rassamyjs — APPROVED** [review]
see prev comment

**Review by rassamyjs — APPROVED** [review]
see prev comment

**Review by begogineni — APPROVED** [review]
I see that the gunicorn package was added. And that many of the Scraper functions were replaced with the dummy data "test". 
There are also 10 fields in the OOCR file that had their name changed to match the Web team's variables.

**Pull request merged**
