### PR TITLE
updating project history with info and resources that are needed to continue

### PR DESCRIPTION
**Pull request by leecrowe**
## Description

Updating project history to give details on what changes were made as well as what what documentation needs to be read to get up and running

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes
[loom](https://www.loom.com/share/51e9d5a2e9b146f588f195d574bbb45c)

### CODE REVIEW

**Review by AZICO — APPROVED** [review]
Good job keeping track of the project flow and putting it in writing!

**Review by ctscofield — APPROVED** [review]
More good documentation that will greatly help the following cohorts.

**Review by jihoover77 — COMMENTED** [review]
This is all well explained and necessary

**Review by Vehmeyer — APPROVED** [review]
Good documentation to add to the ProjectHistory.md file. The bullet points contain concise bits of information to help the people working on the project better understand some of the historical decisions of the project. It's helpful that you added references to other files when appropriate. Nice work!

**Pull request merged**
