### PR TITLE
Typo fix readme

### PR DESCRIPTION
**Pull request by mathewmahoneyds20**
minor typo changes in the VISUALIZATION.INFO link needed an S at the end othrwise clicking takes you to 404 page.

Fixes # (issue)
CHANGED LINKS TO VISUALIZATIONS.INFO on several document pages

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Type of change

[ X] Bug fix (non-breaking change which fixes an issue)

Checklist:
 My code follows the style guidelines of this project
 I have performed a self-review of my own code
 I have removed unnecessary comments/console logs from my code
 I have made corresponding changes to the documentation if necessary (optional)
 My changes generate no new warnings
 I have checked my code and corrected any misspellings
 No duplicate code left within changed files
 Size of pull request kept to a minimum
 Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Vehmeyer — APPROVED** [review]
Good catch! The link was definitely broken, returning a page with a 404. Your update fixes the link. Good work catching this.

**Review by EmilyAFlener — APPROVED** [review]
Small edit to pluralize visualizations. Can approve.

**Review by EmilyAFlener — COMMENTED** [review]
@mathewmahoneyds20 for my learnings, what does the addition of '- docker' do?

**Comment by dylan-rinella** [comment]
Props to finding this small error. Fixed the issue with the link. Good catch

**Pull request merged**
