### PR TITLE
Create SCRAPER_INFO.md

### PR DESCRIPTION
**Pull request by JenFaith**
Added information about functions to documentation

### CODE REVIEW

**Review by BrokenShell — APPROVED** [review]
Outstanding!

**Review by ren-curry — APPROVED** [review]
Excellent start to the function documentation. This should be helpful for the next team to review the codebase.

**Review by Daniel-Fernandez-951 — APPROVED** [review]
Much needed leg-up for future cohorts!

**Review by KWeatherwalks — APPROVED** [review]
Great work here, Jen!
We should get this merged so that everybody can update the info for the functions they worked on.

**Comment by FrankBellamy** [comment]
Great documentation for the next team!

**Pull request merged**
