### PR TITLE
updated judge list

### PR DESCRIPTION
**Pull request by yaobviously**
## Description

Cleaned a few names on the judge list and added several more with the goal of expanding the names recognized by the OCR
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by minh14496 — COMMENTED** [review]
Are these all the judges we need Jason? If there are more, I would suggest you create a file store all those judge and import back to the ocr.

**Comment by WaqasKhwaja** [comment]
🤯 550 deletions and additions. 😄

**Review by KanadeFuzen — COMMENTED** [review]
🤯 550 deletions and additions. 😄

**Comment by yaobviously** [comment]
Thanks for the feedback.

Minh, that's exactly what I did.

**Pull request closed without merging**
