### PR TITLE
Origin/clean up old code

### PR DESCRIPTION
**Pull request by ivan-mihailov**
## Description

This pull request is submitted to delete commented-out code and delete unused libraries in main.py and visualizations.py. In addition, we added a default value of "outcome" to feature_2 in the function get_judge_feature_vis. This fixes a bug when that function is called in main.py

Fixes # (no number assigned)
- Fixes a bug in main.py when the function get_judge_feature_vis is called

Co-authored with @EmilyAFlener in pair-programming session.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/846d96bb93f24010b780743508157efe

Screenshot before removing old endpoint

Before_Removing_Old_Endpoint_Code

Screenshot before removing unused imports in visualizations

Before_Removing_Unused_Imports_Visualizations

Screenshot before adding default value to Feature_2 in get_judge_feature_vis function

Before_Adding_Default_Value_Feature_2

Screenshot after adding default value to Feature_2 in get_judge_feature_vis function

After_Adding_Default_Value_Feature_2

### CODE REVIEW

**Review by jihoover77 — COMMENTED** [review]
These cleanups look great.  I do not see any problems with them.

**Comment by AZICO** [comment]
A detailed explanation of the purpose of the pull request with screenshots is attached. Helpful material for future engineers.

**Review by Vehmeyer — APPROVED** [review]
Nice job of cleaning up unused libraries and removing unneeded comments for a function that is no longer being used. It's important to clean up things that aren't being used in our code, so this is very helpful. I appreciate the screen shots that you added to the PR. It makes it easier to get a quick understanding of what changes are being made. Great work!

**Comment by EmilyAFlener** [comment]
> These cleanups look great. I do not see any problems with them.

Hey @jihoover77 it looks like you must approve these changes for it to move on for @paulstgermain approval. 

John Vehmeyer's is a timely example where you can see his approval directly above his comment. 

I want to make sure you get credit for your contributions!

**Review by jihoover77 — APPROVED** [review]

**Review by jihoover77 — APPROVED** [review]

**Review by jihoover77 — APPROVED** [review]

**Review by jihoover77 — APPROVED** [review]

**Pull request merged**
