### PR TITLE
Update KnownDefects.md to rule out using PyMuPDF

### PR DESCRIPTION
**Pull request by brett-doffing**

### CODE REVIEW

**Comment by brett-doffing** [comment]
Since I didn't quite give a good description of what is actually happening, and it doesn't quite show, I used `<strike></strike>` to cross out the text that was suggesting research of PyMuPDF, and commented on this update.

**Review by BrokenShell — APPROVED** [review]

**Comment by kriegersaurusrex** [comment]
We talked it over with Frank and found the licensing structure for PyMuPDF/GhostScript wouldn't be compatible for the project, and will continue to rely on the pyTesseract library to perform OCR. We've also used a paid service from GCP to convert the documents into text for offline analysis, so work on improving the OCR's speed would be a lower priority task.

**Comment by brett-doffing** [comment]
Re-opening to merge, needs more reviews.

**Review by joeyMckinney — APPROVED** [review]
Looks good.

**Pull request merged**
