### PR TITLE
adding folder for QA testing priority fields

### PR DESCRIPTION
**Pull request by rdukewiesenb**
Friday, 5/14/21, the team will be pushing further optimized versions of the six priority fields, for review and QA testing: 

- Judge(s)
- Court location
- Applicant country of origin
- Location applicant is filing from
- Case type (initial or appellate)
- Protected grounds
- Case outcome

## Type of change

Please delete options that are not relevant.

[ ]  Bug fix (non-breaking change which fixes an issue)
[X]  New feature (non-breaking change which adds functionality)
[ ]  This change requires a documentation update

## Checklist:

- [X ]  My code follows the style guidelines of this project
- [X ]  I have performed a self-review of my own code
- [X ]  I have removed unnecessary comments/console logs from my code
- [X ]  I have made corresponding changes to the documentation if necessary (optional)
- [X ]  My changes generate no new warnings
- [ X]  I have checked my code and corrected any misspellings
- [X ]  No duplicate code left within changed files
- [X ]  Size of pull request kept to a minimum
- [X ]  Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by FrankBellamy — COMMENTED** [review]
Simple addition of a needed folder, looks good.

**Review by JRBOH — APPROVED** [review]
This is a good way for us to stay organized as we are making changes to these features. Thanks for adding it.

**Review by PatrickRaborn — APPROVED** [review]
Read and approved changes to add folder for labs 34 notebooks

**Comment by PatrickRaborn** [comment]
Read and approved changes to add folder for labs 34 notebooks

**Pull request merged**
