### PR TITLE
Simplifying the DS repo to insure smooth data communication and clarity between files.

### PR DESCRIPTION
**Pull request by EmilyAFlener**
## Description

Co-authored with @ivan-mihailov 

This request addresses the following:

- Standardized naming conventions
- Deletion of erroneous files
- Comments to provide contextual clarity where applicable
- PEP8 implementation when beneficial

## Type of change

[X ] New feature (non-breaking change which adds functionality)

## Checklist:

- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have removed unnecessary comments/console logs from my code
- [ X] I have made corresponding changes to the documentation if necessary (optional)
- [X ] My changes generate no new warnings
- [ X] I have checked my code and corrected any misspellings
- [ X] No duplicate code left within changed files
- [X ] Size of pull request kept to a minimum
- [X ] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/76d12506d09f452bb30a61e290c791bb

### CODE REVIEW

**Review by ivan-mihailov — APPROVED** [review]
Good and necessary clean-up of the DS repo which had a lot of unnecessary files and old, unused code. Great Job!

**Review by chandapwes — COMMENTED** [review]
Thorough video/description and a necessary cleanup. Great job.

**Review by mathewmahoneyds20 — CHANGES_REQUESTED** [review]
Can this be broken down into multiple PRs?  Threre is way to many changes and edits to safely approve all grouped together imo.

**Review by marcsaav — APPROVED** [review]
Cleaning up the code as we disuse it is so important to provide readability and ensure a good onboard for future engineers. Nice job!

**Pull request merged**
