### PR TITLE
Update orc.py get_date function

### PR DESCRIPTION
**Pull request by JenFaith**
Simply reformats date output to format requested by backend. Requested format was: 'yyyy-mm-dd'

### CODE REVIEW

**Review by FrankBellamy — APPROVED** [review]
Looks like it does what it says, simple reformatting of the returned string.

**Review by KWeatherwalks — APPROVED** [review]
This PR is important for the API's data formats to be consistent across teams.
It's a small change but necessary.

**Comment by kriegersaurusrex** [comment]
Lines up with meetings we had among multiple parties 🎉

**Review by brett-doffing — APPROVED** [review]
Changes format to 'yyyy-mm-dd'

**Review by kriegersaurusrex — APPROVED** [review]
Thanks for making this change!

**Review by francislabountyjr — APPROVED** [review]
PR changes date format as specified to ensure conventions are shared between teams.

**Pull request merged**
