### PR TITLE
Fix protected grounds

### PR DESCRIPTION
**Pull request by ivan-mihailov**
## Description

This pull request is submitted to refactor the code in the get_protected_grounds function in ocr.py.  The refactor adds a helper function and works to ensure that an MVP feature of significant importance to the stakeholder (the protected grounds on which the case is decided) scrapes such details more accurately (and does not assign all 5 protected grounds to each case). In addition, the refactor also speeds up the get_protected_grounds function by streamlining the code.

Lastly, the PR fixes the correct version of the DS API to "0.39.1"

Fixes # (no number assigned)
- Fixes a bug in ocr.py due to incorrectly scraping protected_grounds from cases

Co-authored in pair-programming sessions with:
@EmilyAFlener
@mathewmahoneyds20
@AZICO
@BrokenShell 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/e4c81d9c238a4658b79e2d25eb025a78

### CODE REVIEW

**Review by dylan-rinella — APPROVED** [review]
Very clean code! Love the comments that explain what is happening within the code! Very thorough loom video as well! Wanted to point that out btw. Great work!

**Review by sirakisaias — APPROVED** [review]
Making sure the scraper works seamlessly is very important since it is the main base of each cases. Updating the DS API version and explanatory comment looks clean too.

**Review by mathewmahoneyds20 — APPROVED** [review]
Double checked work as other contributors edited file and everything is exaclty as it should be. Thanks to everyone who contriibuted each team member definately balanced out a good fix.

**Review by AZICO — APPROVED** [review]
Clean and optimized code! Easy to read and understand

**Review by EmilyAFlener — APPROVED** [review]
Good work all around Ivan. I know we all worked on this together but you are the one who dug into the spacy documentation to make it as robust as possible. Good call on the spelling errors, especially Buddhism, this is a term the scraper is specifically looking for so it needs to be correct. You'll have to tell me more about the removal of text from the match variable. It looks universally applied. I just want to learn the why.

**Review by marcsaav — APPROVED** [review]
Changes look good, keeping a good scraper is a huge part of this application. Great job!

**Pull request merged**
