### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zunerabokhari**
## Description

Adding the dataflow diagram to the README.md so that everyone who works on this project can get a clear understanding of it.

### CODE REVIEW

**Review by TrevorDewalt — APPROVED** [review]
I really like how this turned out. Super clean and simple data flow diagram. Excellent work.

**Review by leecrowe — APPROVED** [review]
Looks great, thank you for taking on this task I know it couldn't have been too easy. Very well done.

**Review by ctscofield — APPROVED** [review]
The data flow diagram looks awesome and it looks like there was a lot of thought that went into making it that way. This will definitely be a huge help to those that will take over the project!

**Review by matthewblackbu — APPROVED** [review]
Looks good to me Its way more intuitive than the last flow

**Review by AD9018 — APPROVED** [review]
Look good to me, simple and clean. Easy to read as well!

**Review by RickyKlusmeier — APPROVED** [review]
Simple and easy to follow for future Labs cohorts

**Pull request merged**
