### PR TITLE
eoir data prep and readme

### PR DESCRIPTION
**Pull request by yaobviously**
## Description

Added a README for the EOIR dataset and included a Notebook demonstrating how to start the process of extracting relevant information.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by minh14496 — CHANGES_REQUESTED** [review]
Jason you upload Pipfile. You can remove it straight from github website

**Review by KanadeFuzen — APPROVED** [review]
Looks fine, but like Minh said, remove the Pipfile first.

**Review by andrewlee977 — APPROVED** [review]
Looks good other than the Pipfile!

**Review by minh14496 — APPROVED** [review]
Perfect Jason. Thanks for the work

**Pull request merged**
