### PR TITLE
A notebook implementing `get_judge()` functionality

### PR DESCRIPTION
**Pull request by brett-doffing**
This is a notebook for Labs 34, to show a basic implementation of searching for judges in initial case documents.

To view the actual notebook here, click on `Files changed`, find the `...` under `Review changes`, and click `View file` from the submenu.

### CODE REVIEW

**Review by JenFaith — APPROVED** [review]
I'm sure this notebook will be very helpful for the next cohort to test out the functionality of get judges

**Review by Daniel-Fernandez-951 — APPROVED** [review]
Note to future cohorts: this will save a lot of time! Thank you, looks great.

**Review by KWeatherwalks — APPROVED** [review]
This is a great addition to help the next team work to improve the functionality for updating a list of judges.

**Comment by rdukewiesenb** [comment]
This notebook will be a great resource on judge retrieval for future data scientists on this product.

**Pull request merged**
