### PR TITLE
Added a notebook for testing the accuracy of `get_panel()`

### PR DESCRIPTION
**Pull request by brett-doffing**
This notebook is used to show the efficacy of finding panel members in case documents. It compares different lists of judges, as search patterns for panel members, using the code that is currently implemented. It then uses a hard-coded list of judges, alongside SpaCy's Pattern Matcher, to achieve results that correctly identify panel members approximately 97% of the time. This shows that the Phrase Matcher should be used instead of the current method.

To view the actual notebook, click on `Files changed`, find the `...` under `Review changes`, and click `View file` from the submenu.

### CODE REVIEW

**Review by KWeatherwalks — APPROVED** [review]
This notebook provides a helpful method for checking the scraper's accuracy against the data manually input by the Labs33 DS team. 
It will be helpful for the next cohort to adapt this to tests for other fields.

**Comment by Daniel-Fernandez-951** [comment]
Thank you for this tool!

**Review by Daniel-Fernandez-951 — APPROVED** [review]
A useful tool, thank you!

**Review by francislabountyjr — APPROVED** [review]
This PR adds a method of verifying scraper accuracy of the get_panel function using manually extracted data as the source of truth. This code can be adapted by future teams in order to test the accuracy of the other scraper functions.

**Review by JenFaith — APPROVED** [review]
Very useful. I think this will be helpful for the next cohort as well!

**Comment by rdukewiesenb** [comment]
This notebook will help data scientists improve the accuracy of the `get_panel()` field, so that database will properly list the appellate judges who reviewed each case.

**Pull request merged**
