### PR TITLE
Refactor ocr.py to scrape for immigration court cases instead of BIA cases

### PR DESCRIPTION
**Pull request by ivan-mihailov**
## Description

This pull request is submitted to change the name of the BIACase class to IJCase class to reflect the decision that the application will not receive BIA appellate cases but will focus on initial immigration court cases.

In addition, the PR refactors the code in the following functions in ocr.py:

get_date
get_outcome
get_application  

These refactors are designed to more accurately scrape data from immigration court cases (as those cases follow a different pattern than BIA cases).

Fixes # (no number assigned)
- Fixes a bug in ocr.py due to path change from BIA cases to immigration cases

Co-authored with @EmilyAFlener and @mathewmahoneyds20 in pair-programming session.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/cebfe73b51fc4bf5946a7ba02ef7f0e0

### CODE REVIEW

**Review by EmilyAFlener — CHANGES_REQUESTED** [review]
Ivan, I don't necessarily have a change request just confirmation that my understanding of the changes is correct.

To confirm in writing: what was formerly lines 335-354 is now a nested if statement, seen in lines 333-349, and the newly created primary if statement is now a negation. 
This move should proactively address the prior blocker that multiple protected grounds were be produced when only one can be in real life.

Changes seen to pluralize or substitute words are to align the scraper with the documentation difference between cases at the IJ level not the BIA level. 
For future readers, BIA is the Board of Immigration Appeals, or secondary judicial level, and IJ is the Immigration Judge, or initial judicial level.

Across the board, it appears variable and cahnges to strings have been applied in all instances.

From here, I will need to go in and further cut code with any BIA reference within the truncated sections and insure they do not affect your new submissions.

**Comment by ivan-mihailov** [comment]
> To confirm in writing: what was formerly lines 335-354 is now a nested if statement, seen in lines 333-349, and the newly created primary if statement is now a negation. This move should proactively address the prior blocker that multiple protected grounds were be produced when only one can be in real life.

Emily, this PR does not address the protected_grounds issue . We discussed it during our session but since this requires more extensive code refactor (writing a new function and adding it to lines 335-354), we did not include it in this PR. We will work on this later today and submit a separate PR.

**Review by EmilyAFlener — APPROVED** [review]

**Comment by EmilyAFlener** [comment]
Thank you for the detail. Makes sense. Code looks good for this PR. Very clean and succinct. Anything that could cause confusion has been removed. Notes to add additional context or rationale to actions taken has been added and is understandable.

**Comment by mathewmahoneyds20** [comment]
Not sure if a coauthor can approve this but I am going to try since even though I assisted I double checked Ivan's work and everything was thoughtfully completed and improves the protected grounds bug.

(I learned a lot in a short time working with Ivan and Emily)

**Review by mathewmahoneyds20 — APPROVED** [review]

**Review by paulstgermain — APPROVED** [review]

**Pull request merged**
