### PR TITLE
Updating the readme with resources as well as adding a visual_info file 

### PR DESCRIPTION
**Pull request by leecrowe**
## Description

Made changes to the way the readmes appear on page making the most relevant ones the first to be seen, added `VISUALIZATIONS_INFO` to explain changes and how each feature works within the `main.py` and `visualizations.py` files.
As well as added each respective team member to the contributions list.**PLEASE LET ME KNOW IF I FORGOT YOU**

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes
[loom](https://www.loom.com/share/89b4fa3c7aee43f08f7dc8923f9ac256)

### CODE REVIEW

**Review by AZICO — APPROVED** [review]
Great job explaining the readme file in detail. Looks awesome

**Review by ctscofield — APPROVED** [review]
Good documentation. I'm sure the following cohort will be extremely grateful for this golden nugget of information.

**Review by willmoon19 — COMMENTED** [review]
This is some really useful information.

**Review by mathewmahoneyds20 — APPROVED** [review]
The more specific details for each item/document/code is a necessity for every following contributor to get a strong understanding on what this application is and what has been completed to that point to be able to continue the evolutionary success of the app.

**Comment by dylan-rinella** [comment]
Thank you for the explanation, very useful for first time viewing your code!

**Review by Vehmeyer — APPROVED** [review]
Nice addition. These details are helpful for the new cohorts to get caught up to speed when they join this project. Thanks for making these updates!

**Pull request merged**
