### PR TITLE
Aws bs deploy

### PR DESCRIPTION
**Pull request by boscolio**

### CODE REVIEW

**Review by rassamyjs — COMMENTED** [review]
Added several versions into the pipfile.
dnspython was added into the pipfile
streamlit changed to version 79 from 78

**Review by rassamyjs — APPROVED** [review]
see prev comment

**Review by begogineni — APPROVED** [review]
Only the pipfile.lock was changed so libraries were being upgraded/added

- Unsure what this change is --- but it looks like the meta hash key was changed. 
- dnspython was added as a library to the Pipfile
- upgraded the soupsieve library from 2.2 to 2.2.1
- upgraded the streamlit library from 0.78.0 to 0.79.0

**Review by begogineni — COMMENTED** [review]
I don't get what this is doing. I'll ask again later and approve if need be.

**Comment by boscolio** [comment]
Dependency changes for the purpose of deployment to AWS Beanstalk.

**Pull request merged**
